version: "3.8"
services:
  mongo-db:
    container_name: ${MONGO_DB_NAME}
    image: mongo:6.0.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./mongo-vol:/data/db
    ports:
      - "27017:27017"
    hostname: mongo
    command: ["--auth"]

  postgres-db:
    image: postgres:16.1-alpine3.18
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres-vol:/var/lib/postgresql/data

volumes:
  mongo-vol:
    external: false
  postgres-vol:
    external: false
