version: "3.8"
services:
  postgres-db:
    image: postgres:16.1-alpine3.18
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres-vol:/var/lib/postgresql/data

  pgAdmin:
    image: dpage/pgadmin4:8.5
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_PASSWORD=superman
      - PGADMIN_DEFAULT_EMAIL=superman@google.com
    ports:
      - "8080:80"
    depends_on:
      - postgres-db

volumes:
  postgres-vol:
    external: false
