version: "3.8"
services:
  mongo-db:
    container_name: ${MONGO_DB_NAME}
    image: mongo:6.0.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./mongo-vol:/data/db
    ports:
      - "27017:27017"
    hostname: mongo
    command: ["--auth"]

  mongo-express:
    depends_on:
      - mongo-db
    image: mongo-express:1.0.2-20-alpine3.19
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: mongo-db
    ports:
      - "8080:8081"
    restart: always
    entrypoint: /bin/sh -c "while ! nc -z mongo-db 27017; do echo 'Waiting for mongo-db...'; sleep 1; done; /docker-entrypoint.sh"
    # command:  /bin/sh -c docker exec -it 07-noc-email-db-mongo-express-1 ping mongo

volumes:
  mongo-vol:
    external: false
